
CREATE TABLE ROLE (
ID INT PRIMARY KEY AUTO_INCREMENT,
TITLE VARCHAR(10) NOT NULL UNIQUE,
DESCRIPTION VARCHAR(65) NOT NULL
);

CREATE TABLE STATUS (
ID INT PRIMARY KEY AUTO_INCREMENT,
TITLE VARCHAR(10) NOT NULL UNIQUE,
DESCRIPTION VARCHAR(65) NOT NULL
);


CREATE TABLE USER (
NICK VARCHAR(20) PRIMARY KEY NOT NULL,
ROLE INT NOT NULL,
CONSTRAINT FK_ROLE_ID
FOREIGN KEY (ROLE) REFERENCES ROLE(ID)
);

CREATE TABLE MESSAGE (
ID INT PRIMARY KEY AUTO_INCREMENT,
USER_FROM VARCHAR(20) NOT NULL,
MESSAGE TEXT NOT NULL,
TIME_STAMP DATETIME NOT NULL,
STATUS INT NOT NULL,
CONSTRAINT FK_USER_FROM_NICK
FOREIGN KEY (USER_FROM) REFERENCES USER(NICK),
CONSTRAINT FK_STATUS_ID
FOREIGN KEY (STATUS) REFERENCES STATUS(ID)
);

CREATE INDEX USER_FROM_FOREING_INDEX 
ON MESSAGE(USER_FROM);

CREATE INDEX ROLE_FOREING_INDEX 
ON USER(ROLE);

CREATE INDEX STATUS_FOREING_INDEX 
ON MESSAGE(STATUS);